DELETE FROM COMMENT;
DELETE FROM PRODUCT;
DELETE FROM CATEGORY;

ALTER TABLE PRODUCT ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE CATEGORY ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE COMMENT ALTER COLUMN ID RESTART WITH 1;
