CREATE SEQUENCE category_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS CATEGORY
(
    id Integer DEFAULT NEXTVAL('category_seq') PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE SEQUENCE product_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS PRODUCT
(
    id Integer DEFAULT NEXTVAL('product_seq') PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    description VARCHAR(100) NOT NULL,
    price Integer,
    category_id Integer,
    FOREIGN KEY (category_id) REFERENCES CATEGORY (id) ON DELETE SET NULL
);


CREATE SEQUENCE comment_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE IF NOT EXISTS COMMENT
(
    id Integer DEFAULT NEXTVAL('comment_seq') PRIMARY KEY,
    text VARCHAR(500) NOT NULL,
    created date CHECK (created  <= CURRENT_DATE),
    product_id Integer,
    FOREIGN KEY (product_id) REFERENCES PRODUCT (id)
);

